name:                PinwheelMatch
version:             0.1.0.0
github:              "githubuser/PinwheelMatch"
license:             BSD3
author:              "Xinhua Zhang"
maintainer:          "xinhua@unm.edu"
copyright:           "2019 Xinhua Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/PinwheelMatch#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.3.0 && < 0.6.0.0
- binary >= 0.8.6.0 && < 0.9.0.0
- conduit >= 1.3.1 && < 1.4.0
- containers >= 0.6.0.1 && < 0.7.0.0
- directory >= 1.3.3.0 && < 1.4.0.0
- filepath >= 1.4.2.1 && < 1.5.0.0
- JuicyPixels >= 3.3.3 && < 4.0.0
- hashable >= 1.2.7.0 && < 1.3.0.0
- hmatrix >= 0.19.0.0 && < 0.20.0.0
- monad-parallel >= 0.7.2.3 && < 0.8.0.0
- parallel >= 3.2.2.0 && < 4.0.0.0
- random >= 1.1 && < 2.0
- repa >= 3.4.1.4 && < 3.5.0.0
- resourcet >= 1.2.2
- text >= 1.2.3.1 && < 1.3.0.0
- unordered-containers >= 0.2.9.0 && < 0.3.0.0
- vector >= 0.12.0.2 && < 0.13.0.0

library:
  source-dirs: src

executables:
  PinwheelMatch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PinwheelMatch

tests:
  PlotDetectedRegion-test:
    main:                PlotDetectedRegion.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is PlotDetectedRegion
    # - -fno-liberate-case
    # - -funfolding-use-threshold1000
    # - -funfolding-keeness-factor1000
    # - -fllvm
    # - -optlo-O3
    dependencies:
    - PinwheelMatch